apiVersion: v1
kind: ReplicationController
metadata:
  name: nginxrc
spec:
  replicas: 2
  template:  #pod template
    metadata:
      labels:
        team: dev
    spec:
      containers:
      - name: nginxcont
        image: nginx
        ports:
        - containerPort: 80
